
#
# NOT GENERATED BY CMTools. Do not run `cmt codemeta.json website.mak` --
# it will overwrite this file and break the site build.
#
# CMTools' template renders ./*.md into HTML beside the sources. This project
# keeps its documentation in docs/ and builds into $(HTDOCS), so the two have
# diverged deliberately. See docs/DEVELOPERS.md.
#
# Makefile for building the documentation website with pandoc.
#
# Sources live in two places:
#
#   docs/*.md   hand-written documentation
#   ./*.md      generated by cmt, which can only write to the repo root
#
# Both are rendered flat into $(HTDOCS) along with the demo pages and the
# runtime assets they load. Nothing in $(HTDOCS) is committed --
# .github/workflows/docs.yml runs this target and uploads the directory.
#
PROJECT = CL-web-components

PANDOC = $(shell which pandoc)

PAGEFIND = $(shell which pagefind)

HTDOCS = _site

DOCS_MD = $(shell ls -1 docs/*.md)

ROOT_MD = $(shell ls -1 *.md)

# Hand-written pages, copied into the site as-is.
STATIC_PAGES = $(shell ls -1 docs/demo_*.html docs/*test*.html)

# Runtime assets the pages load. LICENSE is linked from the page template.
STATIC_FILES = $(shell ls -1 *.js) LICENSE .nojekyll

STATIC_DIRS = css src

build: pagefind

pages: .FORCE
	@mkdir -p $(HTDOCS)
	@if [ ! -f "$(PANDOC)" ]; then echo "pandoc not found, skipping page build"; exit 0; fi
	@for SRC in $(DOCS_MD) $(ROOT_MD); do \
		BASE=$$(basename "$$SRC" .md); \
		OUT="$(HTDOCS)/$$BASE.html"; \
		if [ "$$BASE" = "README" ]; then OUT="$(HTDOCS)/index.html"; fi; \
		echo "$$SRC -> $$OUT"; \
		$(PANDOC) --metadata title="$$BASE" -s --to html5 "$$SRC" -o "$$OUT" \
			--lua-filter=links-to-html.lua \
			--lua-filter=add-col-scope.lua \
			--template=page.tmpl || exit 1; \
	done

static: .FORCE
	@mkdir -p $(HTDOCS)
	cp -p $(STATIC_PAGES) $(STATIC_FILES) $(HTDOCS)/
	cp -Rp $(STATIC_DIRS) $(HTDOCS)/

# Depends on the pages and assets so the index always matches what ships.
pagefind: pages static
	@if [ -f "$(PAGEFIND)" ]; then $(PAGEFIND) --site $(HTDOCS) --force-language en-US --exclude-selectors "nav,header,footer"; fi

clean:
	@rm -rf $(HTDOCS)

.FORCE:
